import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.css"
import UserContextProvider from '@/contexts/userContext'
import { ReactQueryClientProvider } from '@/contexts/reactQueryClientProvider';
import { Toaster } from "@/components/ui/sonner"
import { MicrophoneContextProvider } from '@/contexts/microphone';
import { AudioStoreContextProvider } from '@/contexts/audio-store';
import { DeepgramContextProvider } from '@/contexts/deepgram';
import { MessageMetadataContextProvider } from '@/contexts/message-metadata';
import { NowPlayingContextProvider } from 'react-nowplaying';

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Wanderer - AI powered mock interviewer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <UserContextProvider>
            <MicrophoneContextProvider>
              <AudioStoreContextProvider>
                <NowPlayingContextProvider>
                  <MessageMetadataContextProvider>
                    <DeepgramContextProvider>{children}</DeepgramContextProvider>
                  </MessageMetadataContextProvider>
                </NowPlayingContextProvider>
              </AudioStoreContextProvider>
            </MicrophoneContextProvider>
            <Toaster />
          </UserContextProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
