import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.css"
import UserContextProvider from '@/contexts/userContext'
import { ReactQueryClientProvider } from '@/contexts/reactQueryClientProvider';

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Wanderer - AI powered mock interviewer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
